Repository jenkins-x-plugins/lighthouse-webui-plugin, pull requests merged in 2021-07, with the labels that each got.

#15 fix: make hmac optional
  charts/lighthouse-webui-plugin/templates/deployment.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#16 chore: use correct indent
  charts/lighthouse-webui-plugin/templates/deployment.yaml
Labels: approved, size/XS

#17 chore: use values.yaml template for hmac
  charts/lighthouse-webui-plugin/templates/deployment.yaml
Labels: approved, ok-to-test, size/XS
