Repository jenkins-x-plugins/lighthouse-webui-plugin, pull requests merged in 2021-06, with the labels that each got.

#1 fix(chart): add missing secret for lighthouse hmac token
  charts/lighthouse-webui-plugin/templates/deployment.yaml
  charts/lighthouse-webui-plugin/values.yaml
Labels: approved, size/S

#3 fix(chart): container image is now stored in github registry
  charts/lighthouse-webui-plugin/values.yaml
Labels: approved, size/XS

#6 fix(chart): ensure env values are used
  charts/lighthouse-webui-plugin/templates/deployment.yaml
Labels: approved, size/XS

#8 chore: improve events details
  event.go
  event_handler.go
  store.go
  web/handlers/router.go
  web/static/app.css
  web/static/app.js
  web/templates/events.tmpl
  web/templates/jobs.tmpl
  web/templates/layout.tmpl
Labels: approved, size/L

#9 fix: allow search by event guid
  web/static/app.js
  web/templates/events.tmpl
  web/templates/jobs.tmpl
Labels: approved, size/S

#10 fix: make it clear when a push event deletes a branch
  event_handler.go
  web/templates/events.tmpl
Labels: approved, size/S

#11 feat: implement persistence
  .gitignore
  charts/lighthouse-webui-plugin/templates/deployment.yaml
  charts/lighthouse-webui-plugin/templates/pvc.yaml
  charts/lighthouse-webui-plugin/values.yaml
  cmd/server/main.go
  event.go
  job.go
  store.go
  web/handlers/functions/facets.go
  web/handlers/functions/store.go
  web/handlers/router.go
  web/static/app.css
  web/templates/events.tmpl
  web/templates/jobs.tmpl
Labels: approved, size/XL

#12 fix(chart): ensure args are strings
  charts/lighthouse-webui-plugin/templates/deployment.yaml
Labels: approved, size/XS

#13 fix: add support for Ingress v1
  charts/lighthouse-webui-plugin/templates/ingress.yaml
  charts/lighthouse-webui-plugin/values.yaml
Labels: approved, size/S

#14 docs: add screenshots
  README.md
  docs/screenshots/events.png
  docs/screenshots/jobs.png
  docs/screenshots/merge-history.png
  docs/screenshots/merge-status.png
Labels: approved, size/S
